version: 2
jobs:
  build:
    docker:
      - image: adobe/commerce-cif-ci-env:ci-v0.1.0
    steps:
      - checkout
      - run:
          name: Build
          command: node ci/build.js
      - store_test_results:
          path: runtime/test/results
      - store_artifacts:
          path: runtime/test/results

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/